development:
  adapter: postgresql
  encoding: unicode
  database: saas_development
  pool: 5
  username: development
  password: development

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
